# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='chats',
            field=models.ManyToManyField(to='chat.Chat'),
        ),
    ]
